<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerElKfxjF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerElKfxjF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerElKfxjF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerElKfxjF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerElKfxjF\App_KernelDevDebugContainer([
    'container.build_hash' => 'ElKfxjF',
    'container.build_id' => '5ccbdfae',
    'container.build_time' => 1618497259,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerElKfxjF');
