<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDCOmxiE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDCOmxiE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDCOmxiE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDCOmxiE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDCOmxiE\App_KernelDevDebugContainer([
    'container.build_hash' => 'DCOmxiE',
    'container.build_id' => '6d5f0dce',
    'container.build_time' => 1618412164,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDCOmxiE');
