#index:
#    path: /
#    controller: App\Controller\DefaultController::index
front.show:
  path: /projet/{slug}-{id}
  controller: App\Controller\ProjetController::show
  requirements:
    slug: '[a-z0-9\-]*'
    id: '\d+'
