INSERT INTO `artisan` (`id`, `nom`, `metier`, `description`, `email`) VALUES
(1, 'Rempart', 1, 'Je suis un jeune elelctricie de bonne réputation j\'ai fais plusieurs projets pour des particuliers. ', 'john@doe.fr'),
(3, 'sdffg', 1, 'sdfghjk', 'fdgh@gmail.com'),
(7, 'sdfg', 1, 'zert', 'john@doe.fr'),
(8, 'sdfg', 1, 'zert', 'john@doe.fr'),
(9, 'Abae', 3, 'lfgfkgnlb,; fl,gfh', 'abae@gmail.com'),
(10, 'fghh', 2, 'sfdghjk', 'john@gmail.com'),
(11, 'dfghjk', 5, 'tjk', 'john@gmail.com'),
(12, 'sdfghj', 1, 'dfgh', 'john@gmail.com'),
(13, 'sdfghj', 1, 'dfgh', 'john@gmail.com'),
(14, 'dfgbn', 8, 'qsd', 'dfgh@ggg.com'),
(15, 'drftg', 8, 'sdfgh', 'fff@mail.be'),
(16, 'sdfgh', 1, 's', 'gob@gg.be'),
(17, 'Herbert', 1, 'Je suis très intéressé par votre projet, je suis disponible de temps à temps. Merci de me contacter.', 'herbert@gmail.com'),
(18, 'df', 8, 'sdf', 'df@mail.be'),
(19, 'dfgfhg', 4, 'cvbn,;;:', 'sdfgh@mail.be'),
(20, 'Alberto', 9, 'Bonjour, je suis interessé par votre projet.....', 'alberto@suni.be'),
(21, 'gfhj', 3, 'dsfg', 'tg@gmail.be'),
(22, 'leo', 4, 'je suis fort interessé.....', 'leo@mail.be');
